CREATE OR REPLACE TABLE ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS (
    MERCHANT_NAME           VARCHAR,
    MERCHANT_STATE          VARCHAR,
    MERCHANT_CITY           VARCHAR,
    RISK_SCORE              NUMBER,
    BLOCK_IND               VARCHAR,
    TRANSACTION_ID          VARCHAR,
    BANK                    VARCHAR,
    CARD_NUMBER             VARCHAR,
    AUTHORIZATION_CODE      VARCHAR,
    ACQUIRER_ID             VARCHAR,
    CARD_BRAND              VARCHAR,
    CURRENCY_CD             VARCHAR,
    TRANSACTION_COUNTRY_CD  VARCHAR,
    MERCHANT_ID             VARCHAR,
    REASON_CODE             VARCHAR,
    POS_NUMBER              VARCHAR,
    MERCHANT_CATEGORY_CODE  VARCHAR,
    TRN_DT                  VARCHAR,
    TRANSACTION_TYPE        VARCHAR,
    TRANSACTION_AMOUNT      NUMBER(18,2),
    CARD_LIMIT_TOTAL        NUMBER(18,2),
    CARD_LIMIT_REMAINING    NUMBER(18,2),
    PROCESS_CODE            VARCHAR,

    -- Metadados de rastreabilidade
    SOURCE_FILENAME         VARCHAR,
    INGESTION_TS            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);