CREATE OR REPLACE TASK RAW.SILVER_TRANSACTIONS_TASK
    WAREHOUSE = lab_wh
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_STREAM')
AS
INSERT INTO RAW.SILVER_TRANSACTIONS
    SELECT 
        TRANSACTION_ID,
        BANK,
        CARD_NUMBER,
        TO_TIMESTAMP_NTZ(
        REGEXP_REPLACE(TRN_DT, '^(\\d{4}-\\d{2}-\\d{2}) (\\d{2})(\\d{2}):', '\\1 \\2:\\3:')) AS TRN_DT,
        TRANSACTION_TYPE,
        TRANSACTION_AMOUNT,
        CARD_LIMIT_TOTAL,
        CARD_LIMIT_REMAINING,
        PROCESS_CODE,
        REASON_CODE,
        POS_NUMBER,
        MERCHANT_CATEGORY_CODE,
        CURRENCY_CD,
        TRANSACTION_COUNTRY_CD,
        MERCHANT_ID,
        MERCHANT_NAME,
        MERCHANT_STATE,
        MERCHANT_CITY,
        AUTHORIZATION_CODE,
        ACQUIRER_ID,
        CARD_BRAND,
        RISK_SCORE,
        BLOCK_IND,
        SOURCE_FILENAME,
        INGESTION_TS
    FROM ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_STREAM;