CREATE OR REPLACE TASK RAW.GOLD_TRANSACTIONS_TASK
    WAREHOUSE = lab_wh
    AFTER RAW.SILVER_TRANSACTIONS_TASK
AS
    CREATE OR REPLACE TABLE RAW.GOLD_TRANSACTIONS AS
SELECT
    BANK,
    TO_VARCHAR(TRN_DT, 'YYYY-MM')       AS TRN_DT,
    COUNT(*) AS QTY,
    SUM( CASE WHEN TRANSACTION_TYPE = 'A' AND REASON_CODE = '000' THEN 1 ELSE 0 END ) AS QTY_APPROVED,
    DIV0(SUM( CASE WHEN TRANSACTION_TYPE = 'A' AND REASON_CODE = '000' THEN 1 ELSE 0 END ), COUNT(*)) AS APPROVED_RATE,
    SUM(TRANSACTION_AMOUNT)   AS TRANSACTION_AMOUNT,
    SUM( CASE WHEN TRANSACTION_TYPE = 'A' AND REASON_CODE = '000' THEN TRANSACTION_AMOUNT ELSE 0 END ) AS TRANSACTION_AMOUNT_APPROVED,
    SUM( CASE WHEN TRANSACTION_TYPE = 'A' AND REASON_CODE = '000' THEN TRANSACTION_AMOUNT ELSE 0 END ) - SUM( CASE WHEN TRANSACTION_TYPE = 'O' AND REASON_CODE = '000' THEN TRANSACTION_AMOUNT ELSE 0 END ) AS FATURAMENTO,
    ROUND( AVG(TRANSACTION_AMOUNT),2 ) AS TICKET_MEDIO,
    ROUND( AVG( CASE WHEN TRANSACTION_TYPE = 'A' AND REASON_CODE = '000' THEN TRANSACTION_AMOUNT ELSE 0 END ), 2) AS TICKET_MEDIO_APPROVED
FROM RAW.SILVER_TRANSACTIONS
GROUP BY ALL
ORDER BY BANK, TRN_DT;