ALTER TASK RAW.GOLD_TRANSACTIONS_TASK   RESUME;

ALTER TASK RAW.SILVER_TRANSACTIONS_TASK RESUME;

ALTER PIPE RAW.BRONZE_TRANSACTIONS_PIPE SET PIPE_EXECUTION_PAUSED = FALSE;

ALTER PIPE IF EXISTS ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_PIPE REFRESH;