ALTER PIPE IF EXISTS ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_PIPE SET PIPE_EXECUTION_PAUSED = TRUE;
ALTER TASK IF EXISTS ANTI_FRAUD_DB.RAW.SILVER_TRANSACTIONS_TASK SUSPEND;
ALTER TASK IF EXISTS ANTI_FRAUD_DB.RAW.GOLD_TRANSACTIONS_TASK   SUSPEND;

DROP PIPE IF EXISTS ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_PIPE;
DROP STREAM IF EXISTS ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS_STREAM;
DROP TABLE IF EXISTS ANTI_FRAUD_DB.RAW.BRONZE_TRANSACTIONS;

DROP TASK IF EXISTS ANTI_FRAUD_DB.RAW.SILVER_TRANSACTIONS_TASK;
DROP TASK IF EXISTS ANTI_FRAUD_DB.RAW.GOLD_TRANSACTIONS_TASK;

DROP DATABASE IF EXISTS ANTI_FRAUD_DB